dbHost = "sql.freedb.tech"
dbUser = "freedb_id19870987_admin"
dbPassword = "fgVtMvk6*mE8HjB"
database = "freedb_id19870987_todo"
authIssuer = "https://sts.choreo.dev:443/oauth2/token"
authAudience = [
  "ciwnWuwZfbcdzBUcnkhKvi_mcBUa",
  "https://sts.preview.choreo.dev:443/oauth2/token",
  "https://apim.preview.choreo.dev:443/oauth2/token",
  "https://sts.choreo.dev:443/oauth2/token"
]